language: node_js
sudo: false

script:
  - npm run travis
  - ./integration.sh $APP_PATH

cache:
  directories:
    - node_modules

node_js:
  - "stable"
  - "6"
  - "5"
  - "4"

matrix:
  fast_finish: true

env:
  matrix:
    - INTEGRATION_REPO="https://github.com/discourse/discourse.git" APP_PATH="discourse/jsapp"
    - INTEGRATION_REPO="https://github.com/aptible/ember-json-schema.git" APP_PATH="ember-json-schema/app"
    - INTEGRATION_REPO="https://github.com/offirgolan/ember-cp-validations.git" APP_PATH="ember-cp-validations/app"

before_script:
  - git clone $INTEGRATION_REPO
